name = "t4-api"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
send_metrics = false
main = "src/worker.ts"
account_id = "0e23ccec1650765ea14bdde657b93172"

[[d1_databases]]
binding = "DB"
database_name = "oracule-db"
database_id = "20a0181f-3178-4f1b-85c6-a76e4702b978"
migrations_dir = "migrations"

# The necessary secrets are:
# - APP_URL - for preventing CORS errors
# - JWT_VERIFICATION_KEY - for Supabase @link https://supabase.com
#
# For local development, you can create a file called .dev.vars and use dotenv syntax.
#
# For deployed environments, you can use wrangler secrets to set these values.
# For example:
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# Or use the Cloudflare web interface.
# @link https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-the-dashboard
#
