name = "t4-stack"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
send_metrics = false
route = "app.t4stack.com/*"
workers_dev = false

[env.preview]
name = "t4-stack-preview"
workers_dev = true
